### PR TITLE
[WIP] Remove deprecated IPDB code from the tests.

### PR DESCRIPTION
**Pull request by svinota**
This PR aims to:

* Remove the deprecated IPDB module usage
* Replace raw IPRoute calls with sync NDB calls that are guaranteed to wait until the changes are set up

### CODE REVIEW

**Comment by svinota** [comment]
I see the nose error. Trying to understand why it happens.

**Comment by DimCitus** [comment]
> I see the nose error. Trying to understand why it happens.

Hi @svinota ! Thanks for contributing to pg_auto_failover. Is it possible that your new code requires a more recent version of some of the Python librairies that are installed / available in the testing environment?

```
  File "/home/travis/build/citusdata/pg_auto_failover/tests/network.py", line 101, in _add_bridge
    ndb.interfaces.create(ifname=name, kind="bridge", state="up")
AttributeError: 'Factory' object has no attribute 'create'
```

As seen in https://github.com/citusdata/pg_auto_failover/blob/master/.travis.yml we're using ubuntu bionic OS with Python 3.7 and we `sudo apt-get install python3-pip` and then use https://github.com/citusdata/pg_auto_failover/blob/master/tests/Pipfile and https://github.com/citusdata/pg_auto_failover/blob/master/tests/Pipfile.lock for the Python packages installed with pip for Python 3.7 in there.

**Comment by svinota** [comment]
Yep, I'm setting up a Ubuntu bionic VM in order to properly reproduce the test environment.

**Comment by svinota** [comment]
@DimCitus probably you may have an idea what I have missed.

I updated the `Pipfile` and `Pipfile.lock` files, but now I see in the docker:

```
test@pgtest02:~/pg_auto_failover$ sudo docker run -ti pg_auto_failover_test:latest pip3 list
Package          Version  
---------------- ---------
certifi          2018.8.24
nose             1.3.7    
pip              18.1     
pipenv           11.9.0   
psycopg2         2.7.7    
pyroute2         0.5.2    
setuptools       40.8.0   
virtualenv       15.1.0   
virtualenv-clone 0.3.0    
```

Thus version 0.5.2 despite 0.5.14 in the requirements.

**Comment by svinota** [comment]
Looks like `pipenv` doesn't run in the container 'cause of Python 3.7 instead of 3.6. Not fixing it yet, continue with a workaround in order to focus on the test debug.

**Comment by svinota** [comment]
Got it working, debugging now.

**Comment by svinota** [comment]
Two errors left. Not sure if they are related to the change, could you please take a look:

```
======================================================================
ERROR: test_ssl_cert.test_000_create_monitor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/citusdata/pg_auto_failover/tests/test_ssl_cert.py", line 172, in test_000_create_monitor
    monitor.check_ssl("on", "verify-ca")
  File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 1778, in check_ssl
    return super().check_ssl(ssl, sslmode, monitor=True)
  File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 797, in check_ssl
    pg_settings = self.pg_config_get(pg_settings_names)
  File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 389, in pg_config_get
    for name, setting in self.run_sql_query(q, settings):
  File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 367, in run_sql_query
    cur.execute(query, args)
psycopg2.DataError: malformed array literal: "["ssl", "ssl_ciphers", "ssl_key_file", "ssl_cert_file", "ssl_crl_file", "ssl_ca_file", "primary_conninfo"]"
LINE 1: ...t name, setting from pg_settings where name = any('["ssl", "...
                                                             ^
DETAIL:  "[" must introduce explicitly-specified array dimensions.
```

```
======================================================================
FAIL: test_basic_operation.test_004_init_secondary
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/citusdata/pg_auto_failover/tests/test_basic_operation.py", line 71, in test_004_init_secondary
    eq_(node2.get_nodename(), "b")
AssertionError: 'node_b' != 'b'
```

**Comment by DimCitus** [comment]
> Two errors left. Not sure if they are related to the change, could you please take a look:

Sure! Thanks for the work you're putting in!

> ```
> ======================================================================
> ERROR: test_ssl_cert.test_000_create_monitor
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/python/3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/test_ssl_cert.py", line 172, in test_000_create_monitor
>     monitor.check_ssl("on", "verify-ca")
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 1778, in check_ssl
>     return super().check_ssl(ssl, sslmode, monitor=True)
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 797, in check_ssl
>     pg_settings = self.pg_config_get(pg_settings_names)
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 389, in pg_config_get
>     for name, setting in self.run_sql_query(q, settings):
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py", line 367, in run_sql_query
>     cur.execute(query, args)
> psycopg2.DataError: malformed array literal: "["ssl", "ssl_ciphers", "ssl_key_file", "ssl_cert_file", "ssl_crl_file", "ssl_ca_file", "primary_conninfo"]"
> LINE 1: ...t name, setting from pg_settings where name = any('["ssl", "...
>                                                              ^
> DETAIL:  "[" must introduce explicitly-specified array dimensions.
> ```

Is it possible that psycopg2 has changed the way Python lists are sent as arrays to Postgres in a way that we should adjust the parameters sent in the query from our client code?

> ```
> ======================================================================
> FAIL: test_basic_operation.test_004_init_secondary
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/opt/python/3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "/home/travis/build/citusdata/pg_auto_failover/tests/test_basic_operation.py", line 71, in test_004_init_secondary
>     eq_(node2.get_nodename(), "b")
> AssertionError: 'node_b' != 'b'
> ```

That looks like the node name was actually not changed? You can obtain a full interactive testing environment pretty easily if you're familiar with tmux already: `make cluster` and then you can go to the secondary pane and stop it (`C-c`) and then `pg_autoctl run --name newname` and see what happens. Is it broken in the code or in the tests, or something else is happening?

**Comment by svinota** [comment]
> _Is it possible that psycopg2 has changed the way Python lists are sent as arrays to Postgres in a way that we should adjust the parameters sent in the query from our client code?_

Yes, it is the case. Thanks for the hint, it's a serious issue in pyroute2, fixing.

**Comment by svinota** [comment]
@DimCitus I believe the code is ready for review.

There is one error still in the CI, I couldn't reproduce it, maybe you can take a look as well.

Thanks!

**Review by DimCitus — APPROVED** [review]

**Comment by DimCitus** [comment]
Thanks for your contribution @svinota, I appreciate your work and I'm quite happy that you did modernise our dependency code to pyroute2. I must admit I was fearing I would spend too much time on trying to understand how to achieve this transition myself ;-)

**Pull request merged**
