### PR TITLE
Check return value of strdup calls

### PR DESCRIPTION
**Pull request by danielgustafsson**
Albeit unlikely on modern server systems, memory allocation can still fail and the result, if unchecked, be null pointer dereferences. This adds a check to affected callsites of strdup to ensure allocation was successful, or abort if not.

### CODE REVIEW

**Comment by DimCitus** [comment]
Hi @danielgustafsson ; thanks for your contribution!

Can you have a look at using [ALLOCATION_FAILED_ERROR](https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/defaults.h#L175) instead of the error format you've been using here? It's already used in a couple places: https://github.com/citusdata/pg_auto_failover/search?q=ALLOCATION_FAILED_ERROR&type=code.

**Comment by danielgustafsson** [comment]
> Hi @danielgustafsson ; thanks for your contribution!
> 
> Can you have a look at using [ALLOCATION_FAILED_ERROR](https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/defaults.h#L175) instead of the error format you've been using here? It's already used in a couple places: https://github.com/citusdata/pg_auto_failover/search?q=ALLOCATION_FAILED_ERROR&type=code.

Oh nice, that's a much bette fit. I'll fix that.

**Comment by DimCitus** [comment]
Sorry about that, I missed it before. For clarity, I think I would prefer using `value == NULL` rather than `!value` in the tests. What do you think? I like code better when it's obvious, and `== NULL` can't be more obvious, I believe...

**Comment by danielgustafsson** [comment]
> Sorry about that, I missed it before. For clarity, I think I would prefer using `value == NULL` rather than `!value` in the tests. What do you think? I like code better when it's obvious, and `== NULL` can't be more obvious, I believe...

I don't have strong opinions either way, so I've updated to patch to your preference.

**Review by DimCitus — APPROVED** [review]

**Comment by danielgustafsson** [comment]
Thanks!

**Pull request merged**
