### PR TITLE
Improve docs color contrast for accessibility

### PR DESCRIPTION
**Pull request by jonels-msft**

### CODE REVIEW

**Comment by jonels-msft** [comment]
Don't merge yet, still a work in progress.

**Comment by jonels-msft** [comment]
@DimCitus this is ready for review now.

What I'm most uncertain about is whether Read The Docs will honor the requirements.txt file I added in this PR. I'm using that file to attempt to pick the latest Sphinx and sphinx_rtd_theme packages. We'll need to bump their versions in the future when other accessibility changes get merged upstream.

**Comment by JelteF** [comment]
> What I'm most uncertain about is whether Read The Docs will honor the requirements.txt file I added in this PR.

Based on the ["read the docs" docs](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file) it is possible to do this, but we need to add a `.readthedocs.yaml` file to the repo.

**Comment by jonels-msft** [comment]
Thanks @JelteF !

I tested the change on a branch of citus_docs and confirmed in the build log that RTD installed the right versions. Also checked the result, and the docs rendered fine. So the change should be good for pg_auto_failover docs.

**Review by DimCitus — APPROVED** [review]
Thanks for the accessibility work @jonels-msft ! I did a quick review of the docs created locally with your patch and it looks all good. About the requirements thing on the read the docs website, I have added your branch in their build system and it is now published over at https://pg-auto-failover.readthedocs.io/en/jonels-contrast/ for your review.

**Comment by jonels-msft** [comment]
@dimitri hmm, something went wrong with the PR merge. For instance I don't see `add_css_file()` in docs/conf.py

I'll open a new PR with my changes rebased against master.

**Comment by DimCitus** [comment]
> @dimitri hmm, something went wrong with the PR merge. For instance I don't see `add_css_file()` in docs/conf.py
> 
> I'll open a new PR with my changes rebased against master.

I though I could click “Update Branch” in the GitHub UI and then merge the PR in my TZ, and we've been busy with other things. I'll wait until you ack the current PR before merging then. Feel free to override the GH changes by pushing what you have on top of the current state of the PR, too.

**Comment by jonels-msft** [comment]
I rebased and force pushed. This PR should be good to merge when you're ready.

**Comment by DimCitus** [comment]
You need to do a `make indent` pass and then push again, the auto-formatting check fails on Travis, see https://travis-ci.com/github/citusdata/pg_auto_failover/jobs/502049017

```
$ if [ -n "$LINTING" ]; then black --check .; fi
would reformat docs/conf.py
Oh no! 💥 💔 💥
1 file would be reformatted, 22 files would be left unchanged.
The command "if [ -n "$LINTING" ]; then black --check .; fi" exited with 1.
```

**Pull request merged**
