### PR TITLE
pip install in build-test container

### PR DESCRIPTION
**Pull request by rheaton**
Without this update, the follow error occurs when running `make run-test`

```
docker build				    \
				\
		--target build-test         \
		-t pg_auto_failover_test	\
		.
[+] Building 5.3s (18/18) FINISHED
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 2.76kB                                                                                    0.0s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 34B                                                                                          0.0s
 => [internal] load metadata for docker.io/library/debian:buster-slim                                                     1.2s
 => [internal] load build context                                                                                         0.0s
 => => transferring context: 227.71kB                                                                                     0.0s
 => [build-test  1/13] FROM docker.io/library/debian:buster-slim@sha256:b586cf8c850cada85a47599f08eb34ede4a7c473551fd7c6  0.0s
 => CACHED [build-test  2/13] RUN apt-get update   && apt-get install -y --no-install-recommends     build-essential      0.0s
 => CACHED [build-test  3/13] RUN echo 'create_main_cluster = false' | sudo tee -a /etc/postgresql-common/createcluster.  0.0s
 => CACHED [build-test  4/13] RUN apt-get update && apt-get install -y --no-install-recommends postgresql-11  && rm -rf   0.0s
 => CACHED [build-test  5/13] RUN adduser --disabled-password --gecos '' docker                                           0.0s
 => CACHED [build-test  6/13] RUN adduser docker sudo                                                                     0.0s
 => CACHED [build-test  7/13] RUN adduser docker postgres                                                                 0.0s
 => CACHED [build-test  8/13] RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers                                     0.0s
 => CACHED [build-test  9/13] WORKDIR /usr/src/pg_auto_failover                                                           0.0s
 => CACHED [build-test 10/13] COPY Makefile ./                                                                            0.0s
 => [build-test 11/13] COPY ./src/ ./src                                                                                  0.1s
 => [build-test 12/13] RUN make -s clean && make -s install -j8                                                           3.8s
 => [build-test 13/13] COPY ./tests/ ./tests                                                                              0.0s
 => exporting to image                                                                                                    0.1s
 => => exporting layers                                                                                                   0.1s
 => => writing image sha256:966d1f683d366b0d0568fbfcb8f2bfa7463441ab0646aaf187c911f1f8d20047                              0.0s
 => => naming to docker.io/library/pg_auto_failover_test                                                                  0.0s
docker run					                \
		--name pg_auto_failover_test		    \
		--privileged  -ti --rm			            \
		pg_auto_failover_test			        \
		make -C /usr/src/pg_auto_failover test	\
		TEST=''
make: Entering directory '/usr/src/pg_auto_failover'
sudo -E env "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/11/bin" USER=docker \
	/usr/bin/nosetests3			\
	--verbose				\
	--nocapture				\
	--stop					\
	--where=tests
Failure: ImportError (cannot import name 'NDB' from 'pyroute2' (/usr/lib/python3/dist-packages/pyroute2/__init__.py)) ... ERROR

======================================================================
ERROR: Failure: ImportError (cannot import name 'NDB' from 'pyroute2' (/usr/lib/python3/dist-packages/pyroute2/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/pg_auto_failover/tests/test_auth.py", line 1, in <module>
    import pgautofailover_utils as pgautofailover
  File "/usr/src/pg_auto_failover/tests/pgautofailover_utils.py", line 6, in <module>
    import network
  File "/usr/src/pg_auto_failover/tests/network.py", line 1, in <module>
    from pyroute2 import netns, NDB, netlink, NSPopen
ImportError: cannot import name 'NDB' from 'pyroute2' (/usr/lib/python3/dist-packages/pyroute2/__init__.py)

----------------------------------------------------------------------
Ran 1 test in 0.046s

FAILED (errors=1)
make: *** [Makefile:118: test] Error 1
make: Leaving directory '/usr/src/pg_auto_failover'
make: *** [run-test] Error 2

```

### CODE REVIEW

**Comment by DimCitus** [comment]
I think I prefer the approach I took in another PR under review, at https://github.com/citusdata/pg_auto_failover/pull/661/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557.

Do you want to merge what I did there in this PR, and then we could merge just that change?

**Comment by rheaton** [comment]
@DimCitus Updated!

**Review by DimCitus — COMMENTED** [review]
I see the pip install line in both lines 38 and 46 of the Dockerfile, is it me or should we clean-up some more?

**Comment by rheaton** [comment]
It was a merge conflict, pushing

**Comment by DimCitus** [comment]
It was fixed in yet another PR that I forgot included the fix too, sorry about that: https://github.com/citusdata/pg_auto_failover/pull/664. Closing now, though you did the right thing. Not my favorite kind of git conflict, but well, happens.

**Pull request closed without merging**
