### PR TITLE
Add support for Citus worker specific transitions in IsBeingPromoted.

### PR DESCRIPTION
**Pull request by DimCitus**

### CODE REVIEW

**Comment by JelteF** [comment]
should this also be added in `CandidateNodeIsReadyToStreamWAL`. I would guess yes.

**Comment by DimCitus** [comment]
> should this also be added in `CandidateNodeIsReadyToStreamWAL`. I would guess yes.

Yeah, looks like you're right, thanks! I will note that in this context it's an optimisation rather than a bug: we would react a little later in the FSM. Better to react early though.

**Review by JelteF — APPROVED** [review]

**Comment by JelteF** [comment]
Maybe add a comment to the code about this.

**Review by onderkalaci — APPROVED** [review]

**Comment by DimCitus** [comment]
> Maybe add a comment to the code about this.

Not sure where/what to comment, so I've been lazy and merged thanks to two approvals ;-)

**Pull request merged**
